name: dfa_shop
description: "A sample shop app test task."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  get_it: ^8.2.0
  dio: ^5.9.0
  web_socket_channel: ^3.0.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  hive_ce: ^2.14.0
  hive_ce_flutter: ^1.0.0
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  dio_cache_interceptor: ^4.0.5

  # for WebSocket
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  build_runner: ^2.9.0
  hive_ce_generator: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Stolzl
      fonts:
        - asset: assets/fonts/stolzl_regular.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
